### PR TITLE
Rust 2021 Edition

### PR DESCRIPTION
**Pull request by djmitche**
This turned out to be pretty easy.  No need to merge this until October when the edition is stable.

### CODE REVIEW

**Comment by petemoore** [comment]
@djmitche Is this still meant to be draft? Are you still working on this?

**Comment by djmitche** [comment]
Ah, I was waiting until the draft was stable.  I can update the PR (we might as well use a newer Rust).

**Comment by djmitche** [comment]
(or someone else can -- I don't mind!)

**Comment by djmitche** [comment]
2021 is stable now, so I've marked this as ready for review, @lotas.

**Comment by djmitche** [comment]
Sorry, I don't know why I pinged you lotas -- switching to @petemoore :)

**Review by petemoore — APPROVED** [review]
Looks great, many thanks!

**Pull request merged**
