### PR TITLE
Update ring to 0.14.5

### PR DESCRIPTION
**Pull request by eoger**
ring yanks old versions regularly and will yank 0.13.5 soon (https://github.com/briansmith/ring/issues/774).
This PR updates ring to the latest version.

### CODE REVIEW

**Comment by djmitche** [comment]
Looks like we need a new rust-hawk-test docker image, too.  I assume tests pass with a newer rust?

**Comment by eoger** [comment]
Yup `cargo test --all --verbose` passes, would it be possible to upload this version on crates.io too?

**Comment by djmitche** [comment]
Sure!  I want to fix CI first, then I'll do a release.

**Comment by djmitche** [comment]
released as v1.0.5

**Comment by eoger** [comment]
Thank you!

**Pull request merged**
