### PR TITLE
remove a println! in production code

### LINKED ISSUE #12: Make it possible to turn off the println! statements
There's some `println!` invocations in this crate that show up in our logs. Ideally we want our all our log lines to be mozlog-parseable so they're kind of annoying in that sense. And they mess up the output from `cargo test` a bit too.

Would you be open to a PR that made them turn-offable? Or, if they're just a hangover from old debugging stuff that's no longer needed, a PR that removed them? I'm happy to do either if you're ok with it.

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #12.

@philbooth this is the only one I find.

### CODE REVIEW

**Comment by philbooth** [comment]
Ah yeah, that's the one, I hadn't looked for how many there actually are when I opened #12. Thanks!

**Comment by djmitche** [comment]
Is this worthy of its own release or do you suspect there will be more changes coming?

**Comment by philbooth** [comment]
Well it's definitely not urgent, so no rush in that sense. But also I'm not aware of any imminent plans to open PRs for the other stuff that was discussed, so there's no need to hold off releasing either (as far as I know).

**Comment by djmitche** [comment]
I'll loop back in a few days and make a patch release, then.

**Comment by djmitche** [comment]
v1.0.4 :)

**Pull request merged**
